version: '3.8'

services:
  otel-collector:
    image: otel/opentelemetry-collector:0.37.1
    container_name: otel-collector
    volumes:
      - ./otel-collector:/tmp
    command:
      - '--config=/tmp/otel-collector.yaml'
    restart: unless-stopped
    ports:
      - "55690:55690"
    labels:
      org.label-schema.group: "monitoring"